"""Cap nhat giam gia

Revision ID: 09b9a19b1085
Revises: 53a0e0b93937
Create Date: 2026-01-12 01:53:14.222556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b9a19b1085'
down_revision: Union[str, Sequence[str], None] = '53a0e0b93937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discounts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.drop_column('discounts', 'category_id')
    # ### end Alembic commands ###
