"""add is_active to product_detail

Revision ID: 21b3e0a8869c
Revises: c4e8f9a1b2d3
Create Date: 2026-03-24 23:43:02.585787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b3e0a8869c'
down_revision: Union[str, Sequence[str], None] = 'c4e8f9a1b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_conversations_last_message_id_messages', 'conversations', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('product_details', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'is_active')
    op.drop_constraint('fk_conversations_last_message_id_messages', 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
