"""cap nhat bang dicounts, evaluates, order_discounts

Revision ID: 5203d1b8727d
Revises: 1af47ae4d552
Create Date: 2025-12-27 15:19:14.663131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5203d1b8727d'
down_revision: Union[str, Sequence[str], None] = '1af47ae4d552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('order_discounts_ibfk_1'), 'order_discounts', type_='foreignkey')
    op.create_foreign_key(None, 'order_discounts', 'discounts', ['discount_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_discounts', type_='foreignkey')
    op.create_foreign_key(op.f('order_discounts_ibfk_1'), 'order_discounts', 'discounts', ['discount_id'], ['id'])
    op.drop_column('evaluates', 'updated_at')
    # ### end Alembic commands ###
