"""Cap nhat phieu nhap

Revision ID: 53a0e0b93937
Revises: bc2d3a6e8007
Create Date: 2026-01-10 22:50:48.069077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53a0e0b93937'
down_revision: Union[str, Sequence[str], None] = 'bc2d3a6e8007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_details', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('receipt_details', sa.Column('color_id', sa.Integer(), nullable=True))
    op.add_column('receipt_details', sa.Column('size_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('receipt_details_ibfk_1'), 'receipt_details', type_='foreignkey')
    op.create_foreign_key(None, 'receipt_details', 'colors', ['color_id'], ['id'])
    op.create_foreign_key(None, 'receipt_details', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'receipt_details', 'sizes', ['size_id'], ['id'])
    op.drop_column('receipt_details', 'product_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_details', sa.Column('product_detail_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'receipt_details', type_='foreignkey')
    op.drop_constraint(None, 'receipt_details', type_='foreignkey')
    op.drop_constraint(None, 'receipt_details', type_='foreignkey')
    op.create_foreign_key(op.f('receipt_details_ibfk_1'), 'receipt_details', 'product_details', ['product_detail_id'], ['id'])
    op.drop_column('receipt_details', 'size_id')
    op.drop_column('receipt_details', 'color_id')
    op.drop_column('receipt_details', 'product_id')
    # ### end Alembic commands ###
