"""Cap nhat image_url

Revision ID: 55cbc3935f1f
Revises: 7552904fcd13
Create Date: 2026-01-06 21:14:23.296441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cbc3935f1f'
down_revision: Union[str, Sequence[str], None] = '7552904fcd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_url', sa.Column('color_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image_url', 'colors', ['color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_url', type_='foreignkey')
    op.drop_column('image_url', 'color_id')
    # ### end Alembic commands ###
