"""Cap nhat bang orders, delivery_info, paytment_methods

Revision ID: 5c9f497eae08
Revises: c8d5f2b9a2a6
Create Date: 2025-12-25 23:45:12.612732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9f497eae08'
down_revision: Union[str, Sequence[str], None] = 'c8d5f2b9a2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('delivery_info_ibfk_1'), 'delivery_info', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_info', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_info', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_info_ibfk_1'), 'delivery_info', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
