"""tao bang vnpay_transactions

Revision ID: 7eaf107e7586
Revises: 09b9a19b1085
Create Date: 2026-01-13 23:22:36.873800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaf107e7586'
down_revision: Union[str, Sequence[str], None] = '09b9a19b1085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vnpay_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('txn_ref', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('response_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('transaction_no', sa.String(length=32), nullable=True),
    sa.Column('bank_code', sa.String(length=20), nullable=True),
    sa.Column('pay_date', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnpay_transactions_id'), 'vnpay_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_vnpay_transactions_order_id'), 'vnpay_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_vnpay_transactions_txn_ref'), 'vnpay_transactions', ['txn_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vnpay_transactions_txn_ref'), table_name='vnpay_transactions')
    op.drop_index(op.f('ix_vnpay_transactions_order_id'), table_name='vnpay_transactions')
    op.drop_index(op.f('ix_vnpay_transactions_id'), table_name='vnpay_transactions')
    op.drop_table('vnpay_transactions')
    # ### end Alembic commands ###
