"""Cap nhat image_url

Revision ID: 8bf3d01cf474
Revises: b5a0aef7ad73
Create Date: 2025-12-30 22:01:21.503110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf3d01cf474'
down_revision: Union[str, Sequence[str], None] = 'b5a0aef7ad73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_url', sa.Column('public_id', sa.String(length=255), nullable=False))
    op.add_column('receipts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'updated_at')
    op.drop_column('image_url', 'public_id')
    # ### end Alembic commands ###
