"""Cap nhat xoa stock_quantity va chỉnh sua kho

Revision ID: bc2d3a6e8007
Revises: b4da62be42a8
Create Date: 2026-01-10 22:42:30.478182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc2d3a6e8007'
down_revision: Union[str, Sequence[str], None] = 'b4da62be42a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'stock_quantity')
    op.add_column('warehouse_details', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('warehouse_details', sa.Column('color_id', sa.Integer(), nullable=True))
    op.add_column('warehouse_details', sa.Column('size_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('warehouse_details_ibfk_1'), 'warehouse_details', type_='foreignkey')
    op.create_foreign_key(None, 'warehouse_details', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'warehouse_details', 'sizes', ['size_id'], ['id'])
    op.create_foreign_key(None, 'warehouse_details', 'colors', ['color_id'], ['id'])
    op.drop_column('warehouse_details', 'product_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_details', sa.Column('product_detail_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouse_details', type_='foreignkey')
    op.drop_constraint(None, 'warehouse_details', type_='foreignkey')
    op.drop_constraint(None, 'warehouse_details', type_='foreignkey')
    op.create_foreign_key(op.f('warehouse_details_ibfk_1'), 'warehouse_details', 'product_details', ['product_detail_id'], ['id'])
    op.drop_column('warehouse_details', 'size_id')
    op.drop_column('warehouse_details', 'color_id')
    op.drop_column('warehouse_details', 'product_id')
    op.add_column('product_details', sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
