"""Them gia vao bien the san pham

Revision ID: daf2f6a4a138
Revises: 32042d410ddb
Create Date: 2025-12-24 01:32:56.409355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf2f6a4a138'
down_revision: Union[str, Sequence[str], None] = '32042d410ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'price')
    # ### end Alembic commands ###
