"""cap nhat bang dicounts, evaluates, order_discounts

Revision ID: f0227cbaa8b1
Revises: 5203d1b8727d
Create Date: 2025-12-27 15:24:04.999270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0227cbaa8b1'
down_revision: Union[str, Sequence[str], None] = '5203d1b8727d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_discounts', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order_discounts', 'discount_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('order_discounts_ibfk_2'), 'order_discounts', type_='foreignkey')
    op.create_foreign_key(None, 'order_discounts', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_discounts', type_='foreignkey')
    op.create_foreign_key(op.f('order_discounts_ibfk_2'), 'order_discounts', 'orders', ['order_id'], ['id'])
    op.alter_column('order_discounts', 'discount_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_discounts', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
